
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The target system is: Generic -  - arm
      The host system is: Darwin - 21.6.0 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/local/bin/arm-none-eabi-gcc -fdata-sections;-ffunction-sections;-fsigned-char;-fmessage-length=0;-ffreestanding
      Build flags: 
      Id flags:  
      
      The output was:
      1
      /usr/local/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ld: cannot find crt0.o: No such file or directory
      /usr/local/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ld: cannot find -lc: No such file or directory
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/local/bin/arm-none-eabi-gcc -fdata-sections;-ffunction-sections;-fsigned-char;-fmessage-length=0;-ffreestanding
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        /Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/3.31.6/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/CMakeScratch/TryCompile-szY7Mc"
      binary: "/Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/CMakeScratch/TryCompile-szY7Mc"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/CMakeScratch/TryCompile-szY7Mc'
        
        Run Build Command(s): /Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -E env VERBOSE=1 /usr/local/bin/gmake -f Makefile cmTC_126ed/fast
        /usr/local/bin/gmake  -f CMakeFiles/cmTC_126ed.dir/build.make CMakeFiles/cmTC_126ed.dir/build
        gmake[1]: Entering directory '/Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/CMakeScratch/TryCompile-szY7Mc'
        Building C object CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj
        /usr/local/bin/arm-none-eabi-gcc -fdata-sections -ffunction-sections -fsigned-char -fmessage-length=0 -ffreestanding   -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj -c /Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeCCompilerABI.c
        Using built-in specs.
        COLLECT_GCC=/usr/local/bin/arm-none-eabi-gcc
        Target: arm-none-eabi
        Configured with: ../configure --target=arm-none-eabi --prefix=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0 --infodir=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/share/info/arm-none-eabi --disable-nls --without-headers --with-as=/usr/local/opt/arm-none-eabi-binutils/bin/arm-none-eabi-as --with-ld=/usr/local/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ld --enable-languages=c,c++,objc,lto --enable-lto --enable-multilib --with-multilib-list=aprofile,rmprofile --with-system-zlib --with-zstd --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0 --libdir=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib
        Thread model: single
        Supported LTO compression algorithms: zlib zstd
        gcc version 14.2.0 (GCC) 
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-fdata-sections' '-ffunction-sections' '-fsigned-char' '-fmessage-length=0' '-ffreestanding' '-v' '-o' 'CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj' '-c' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t' '-dumpdir' 'CMakeFiles/cmTC_126ed.dir/'
         /usr/local/Cellar/arm-none-eabi-gcc/14.2.0/libexec/gcc/arm-none-eabi/14.2.0/cc1 -quiet -v -D__USES_INITFINI__ /Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeCCompilerABI.c -quiet -dumpdir CMakeFiles/cmTC_126ed.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -mcpu=arm7tdmi -mfloat-abi=soft -marm -mlibarch=armv4t -march=armv4t -version -fdiagnostics-color=always -fdata-sections -ffunction-sections -fsigned-char -fmessage-length=0 -ffreestanding -o /var/folders/pv/f5nswqyn7wg2j5n_wh1dl_jm0000gp/T//ccocYbbx.s
        GNU C17 (GCC) version 14.2.0 (arm-none-eabi)
        	compiled by GNU C version Apple LLVM 14.0.0 (clang-1400.0.29.202), GMP version 6.3.0, MPFR version 4.2.2, MPC version 1.3.1, isl version isl-0.27-GMP
        
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/sys-include"
        ignoring nonexistent directory "/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include
         /usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include-fixed
        End of search list.
        Compiler executable checksum: 4ad1ba63a15da174897c0d747b72d219
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-fdata-sections' '-ffunction-sections' '-fsigned-char' '-fmessage-length=0' '-ffreestanding' '-v' '-o' 'CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj' '-c' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t' '-dumpdir' 'CMakeFiles/cmTC_126ed.dir/'
         /usr/local/opt/arm-none-eabi-binutils/bin/arm-none-eabi-as -v -march=armv4t -mfloat-abi=soft -meabi=5 -o CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj /var/folders/pv/f5nswqyn7wg2j5n_wh1dl_jm0000gp/T//ccocYbbx.s
        GNU assembler version 2.44 (arm-none-eabi) using BFD version (GNU Binutils) 2.44
        COMPILER_PATH=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/libexec/gcc/arm-none-eabi/14.2.0/:/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/libexec/gcc/arm-none-eabi/14.2.0/:/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/libexec/gcc/arm-none-eabi/:/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/:/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/
        LIBRARY_PATH=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-fdata-sections' '-ffunction-sections' '-fsigned-char' '-fmessage-length=0' '-ffreestanding' '-v' '-o' 'CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj' '-c' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t' '-dumpdir' 'CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.'
        Linking C static library libcmTC_126ed.a
        /Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -P CMakeFiles/cmTC_126ed.dir/cmake_clean_target.cmake
        /Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_126ed.dir/link.txt --verbose=1
        /usr/local/bin/arm-none-eabi-ar qc libcmTC_126ed.a CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj
        /usr/local/bin/arm-none-eabi-ranlib libcmTC_126ed.a
        gmake[1]: Leaving directory '/Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/CMakeScratch/TryCompile-szY7Mc'
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:182 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include]
          add: [/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include-fixed]
        end of search list found
        collapse include dir [/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include] ==> [/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include]
        collapse include dir [/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include-fixed] ==> [/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include-fixed]
        implicit include dirs: [/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include;/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include-fixed]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?))("|,| |$)]
        ignore line: [Change Dir: '/Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/CMakeScratch/TryCompile-szY7Mc']
        ignore line: []
        ignore line: [Run Build Command(s): /Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -E env VERBOSE=1 /usr/local/bin/gmake -f Makefile cmTC_126ed/fast]
        ignore line: [/usr/local/bin/gmake  -f CMakeFiles/cmTC_126ed.dir/build.make CMakeFiles/cmTC_126ed.dir/build]
        ignore line: [gmake[1]: Entering directory '/Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/CMakeScratch/TryCompile-szY7Mc']
        ignore line: [Building C object CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj]
        ignore line: [/usr/local/bin/arm-none-eabi-gcc -fdata-sections -ffunction-sections -fsigned-char -fmessage-length=0 -ffreestanding   -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj -c /Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeCCompilerABI.c]
        ignore line: [Using built-in specs.]
        ignore line: [COLLECT_GCC=/usr/local/bin/arm-none-eabi-gcc]
        ignore line: [Target: arm-none-eabi]
        ignore line: [Configured with: ../configure --target=arm-none-eabi --prefix=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0 --infodir=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/share/info/arm-none-eabi --disable-nls --without-headers --with-as=/usr/local/opt/arm-none-eabi-binutils/bin/arm-none-eabi-as --with-ld=/usr/local/opt/arm-none-eabi-binutils/bin/arm-none-eabi-ld --enable-languages=c,c++,objc,lto --enable-lto --enable-multilib --with-multilib-list=aprofile,rmprofile --with-system-zlib --with-zstd --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0 --libdir=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib]
        ignore line: [Thread model: single]
        ignore line: [Supported LTO compression algorithms: zlib zstd]
        ignore line: [gcc version 14.2.0 (GCC) ]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-fdata-sections' '-ffunction-sections' '-fsigned-char' '-fmessage-length=0' '-ffreestanding' '-v' '-o' 'CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj' '-c' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t' '-dumpdir' 'CMakeFiles/cmTC_126ed.dir/']
        ignore line: [ /usr/local/Cellar/arm-none-eabi-gcc/14.2.0/libexec/gcc/arm-none-eabi/14.2.0/cc1 -quiet -v -D__USES_INITFINI__ /Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeCCompilerABI.c -quiet -dumpdir CMakeFiles/cmTC_126ed.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -mcpu=arm7tdmi -mfloat-abi=soft -marm -mlibarch=armv4t -march=armv4t -version -fdiagnostics-color=always -fdata-sections -ffunction-sections -fsigned-char -fmessage-length=0 -ffreestanding -o /var/folders/pv/f5nswqyn7wg2j5n_wh1dl_jm0000gp/T//ccocYbbx.s]
        ignore line: [GNU C17 (GCC) version 14.2.0 (arm-none-eabi)]
        ignore line: [	compiled by GNU C version Apple LLVM 14.0.0 (clang-1400.0.29.202)  GMP version 6.3.0  MPFR version 4.2.2  MPC version 1.3.1  isl version isl-0.27-GMP]
        ignore line: []
        ignore line: [GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072]
        ignore line: [ignoring nonexistent directory "/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/sys-include"]
        ignore line: [ignoring nonexistent directory "/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include]
        ignore line: [ /usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/include-fixed]
        ignore line: [End of search list.]
        ignore line: [Compiler executable checksum: 4ad1ba63a15da174897c0d747b72d219]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-fdata-sections' '-ffunction-sections' '-fsigned-char' '-fmessage-length=0' '-ffreestanding' '-v' '-o' 'CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj' '-c' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t' '-dumpdir' 'CMakeFiles/cmTC_126ed.dir/']
        ignore line: [ /usr/local/opt/arm-none-eabi-binutils/bin/arm-none-eabi-as -v -march=armv4t -mfloat-abi=soft -meabi=5 -o CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj /var/folders/pv/f5nswqyn7wg2j5n_wh1dl_jm0000gp/T//ccocYbbx.s]
        ignore line: [GNU assembler version 2.44 (arm-none-eabi) using BFD version (GNU Binutils) 2.44]
        ignore line: [COMPILER_PATH=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/libexec/gcc/arm-none-eabi/14.2.0/:/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/libexec/gcc/arm-none-eabi/14.2.0/:/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/libexec/gcc/arm-none-eabi/:/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/:/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/]
        ignore line: [LIBRARY_PATH=/usr/local/Cellar/arm-none-eabi-gcc/14.2.0/lib/gcc/arm-none-eabi/14.2.0/]
        ignore line: [COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-fdata-sections' '-ffunction-sections' '-fsigned-char' '-fmessage-length=0' '-ffreestanding' '-v' '-o' 'CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj' '-c' '-mcpu=arm7tdmi' '-mfloat-abi=soft' '-marm' '-mlibarch=armv4t' '-march=armv4t' '-dumpdir' 'CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.']
        ignore line: [Linking C static library libcmTC_126ed.a]
        ignore line: [/Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -P CMakeFiles/cmTC_126ed.dir/cmake_clean_target.cmake]
        ignore line: [/Applications/CLion.app/Contents/bin/cmake/mac/x64/bin/cmake -E cmake_link_script CMakeFiles/cmTC_126ed.dir/link.txt --verbose=1]
        ignore line: [/usr/local/bin/arm-none-eabi-ar qc libcmTC_126ed.a CMakeFiles/cmTC_126ed.dir/CMakeCCompilerABI.c.obj]
        ignore line: [/usr/local/bin/arm-none-eabi-ranlib libcmTC_126ed.a]
        ignore line: [gmake[1]: Leaving directory '/Users/yassientawfik/Documents/Career/Projects/Semester_06_Projects/Embedded System/stm32f4-template-macos/cmake-build-debug-arm-stm32/CMakeFiles/CMakeScratch/TryCompile-szY7Mc']
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1237 (message)"
      - "/Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:9 (enable_language)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-none-eabi-gcc (GCC) 14.2.0
      Copyright (C) 2024 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
